turtlepick.engine.base-url=http://localhost:9000
turtlepick.engine.meta.timeout-ms=3000

turtlepick.agent.server-id=kjspringweb-local
turtlepick.agent.app-name=kjspringweb
turtlepick.agent.git.repo-root=.

turtlepick.agent.logging.dir=./turtlepick-logs
turtlepick.agent.logging.rolling.interval-minutes=1
turtlepick.agent.logging.verbose-field-names=true
turtlepick.agent.error.user-frame-packages=com.kjweb
turtlepick.agent.error.args.enabled=true
turtlepick.agent.error.args.max-length=10000
turtlepick.agent.error.args.exclude-classes=java.io.InputStream,java.io.Reader,java.io.File,java.nio.ByteBuffer,org.springframework.web.multipart.MultipartFile,byte[],char[]

turtlepick.agent.instrumentation.http=true
turtlepick.agent.instrumentation.service=true
turtlepick.agent.instrumentation.sql.datasource-proxy=true
turtlepick.agent.instrumentation.sql.mybatis-interceptor=false

